### ISSUE TITLE
python --version writes to stderr, how to catch that?

### ISSUE THREAD

**Issue by simonw** [simonw/xkcd-1987#1]
That's what this line is trying to do: https://github.com/simonw/xkcd-1987/blob/d2633c242de8e658c50d836db56b3a83ffa9267d/xkcd-1987.sh#L4

**Comment by simonw** [comment]
That syntax works under `zsh` - maybe write the whole script in that? Is `zsh` available on macOS before it replaced `bash` as the default shell?

```
% echo "python --version:" $( { python --version } 2>&1 )  
python --version: Python 2.7.16
```

**Comment by simonw** [comment]
When run as `bash` it gives this error:
```
./xkcd-1987.sh: command substitution: line 6: syntax error: unexpected end of file
python --version:
```

**Comment by imomaliev** [comment]
Hi! Could you please explain, why are you doing

```
echo "python --version:" $( { python --version } 2>&1 )
```
instead of this

```
echo "python --version:" $( python --version 2>&1 )
```
?

**Comment by simonw** [comment]
That fixed it, thank you!
